<dd data-name="button"><a lay-href="index.php?m=applib&c=admin_addloginuser&a=carsoso">批量查询</a></dd>
<dd data-name="button"><a lay-href="index.php?m=applib&c=admin_addloginuser&a=caroff">批量封卡</a></dd>
<dd data-name="button"><a lay-href="index.php?m=applib&c=admin_addloginuser&a=caron">批量解冻</a></dd>
<dd data-name="button"><a lay-href="index.php?m=applib&c=admin_addloginuser&a=cardel">批量删除</a></dd>