{
"agentMenu": [
{"id":"console","dataName":"console","active":1,"name":"中控台","icon":"layui-icon-home","link":"index.php?m=agent&c=main&a=info"},
{"id":"card_manage","dataName":"get","name":"卡管理","icon":"layui-icon-layouts","link":"index.php?m=agent&c=CardManageFeature&a=table"},
{"id":"make_card_balance","dataName":"get","name":"余额制卡","icon":"layui-icon-cart-simple","link":"index.php?m=agent&c=MakeCardBalanceFeature&a=table"},
{"id":"make_card_stock","dataName":"get","name":"库存制卡","icon":"layui-icon-add-1","link":"index.php?m=agent&c=MakeCardStockFeature&a=table"},
{"id":"balance_recharge","dataName":"get","name":"余额充值","icon":"layui-icon-add-circle-fine","link":"index.php?m=agent&c=BalanceRechargeFeature&a=table"},
{"id":"my_users","dataName":"home_user","name":"我的用户管理","icon":"layui-icon-group","children":[
{"id":"my_users_table","dataName":"console","name":"我的注册用户","link":"index.php?m=agent&c=MyUsersTableFeature&a=table"},
{"id":"software_users_table","dataName":"console","name":"间接软件用户","link":"index.php?m=agent&c=SoftwareUsersTableFeature&a=table"},
{"id":"invite_users","dataName":"console","name":"邀请推广用户","link":"index.php?m=agent&c=InviteUsersFeature&a=table"}
]},
{"id":"my_agents","dataName":"home","name":"我的代理","icon":"layui-icon-user","children":[
{"id":"my_agent_list","dataName":"console","name":"我的代理列表","link":"index.php?m=agent&c=MyAgentListFeature&a=table"},
{"id":"add_agent","dataName":"console","name":"添加新代理","link":"index.php?m=agent&c=AddAgentFeature&a=table"}
]},
{"id":"finance","dataName":"user","name":"财务管理","icon":"layui-icon-release","children":[
{"id":"card_account_stats","name":"卡通过账号统计","link":"index.php?m=agent&c=CardAccountStatsFeature&a=table"},
{"id":"card_note_usage_stats","name":"卡备注使用统计","link":"index.php?m=agent&c=CardNoteUsageStatsFeature&a=table"},
{"id":"card_account_note_stats","name":"卡账号备注统计","link":"index.php?m=agent&c=CardAccountNoteStatsFeature&a=table"},
{"id":"commission_logs","name":"分佣金收入记录","link":"index.php?m=agent&c=CommissionLogsFeature&a=table"}
]},
{"id":"tools","dataName":"user","name":"代理工具","icon":"layui-icon-star","children":[
{"id":"batch_query","name":"批量查询","link":"index.php?m=agent&c=BatchQueryFeature&a=table"},
{"id":"batch_freeze","name":"批量冻结","link":"index.php?m=agent&c=BatchFreezeFeature&a=table"},
{"id":"batch_unfreeze","name":"批量解冻","link":"index.php?m=agent&c=BatchUnfreezeFeature&a=table"},
{"id":"batch_delete","name":"批量删除","link":"index.php?m=agent&c=BatchDeleteFeature&a=table"},
{"id":"unbind_user","name":"解除用户绑定","link":"index.php?m=agent&c=UnbindUserFeature&a=table"},
{"id":"user_card_renew_recharge","name":"用户卡密续费充值","link":"index.php?m=agent&c=UserCardRenewRechargeFeature&a=table"}
]}
]
}
